# permissions for end users to view queryconnectors.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: search-ruler
    app.kubernetes.io/managed-by: kustomize
  name: queryconnector-viewer-role
rules:
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - queryconnectors
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - queryconnectors/status
  verbs:
  - get
