---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - events
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - events.k8s.io
  resources:
  - events
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - clusterqueryconnectors
  - queryconnectors
  - ruleractions
  - searchrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - clusterqueryconnectors/finalizers
  - queryconnectors/finalizers
  - ruleractions/finalizers
  - searchrules/finalizers
  verbs:
  - update
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - clusterqueryconnectors/status
  - queryconnectors/status
  - ruleractions/status
  - searchrules/status
  verbs:
  - get
  - patch
  - update
