---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - searchruleractions
  - searchrulerqueryconnectors
  - searchrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - searchruleractions/finalizers
  - searchrulerqueryconnectors/finalizers
  - searchrules/finalizers
  verbs:
  - update
- apiGroups:
  - searchruler.prosimcorp.com
  resources:
  - searchruleractions/status
  - searchrulerqueryconnectors/status
  - searchrules/status
  verbs:
  - get
  - patch
  - update
