apiVersion: searchruler.prosimcorp.com/v1alpha1
kind: QueryConnector
metadata:
  labels:
    app.kubernetes.io/name: search-ruler
    app.kubernetes.io/managed-by: kustomize
  name: queryconnector-sample
spec:
  url: "https://127.0.0.1:9200"
  headers: {}
  tlsSkipVerify: true
  credentials:

    # Interval to check secret credentials for any changes
    #syncInterval: 1m

    secretRef:
      name: elasticsearch-main-credentials
      keyUsername: username
      keyPassword: password
