apiVersion: searchruler.prosimcorp.com/v1alpha1
kind: RulerAction
metadata:
  labels:
    app.kubernetes.io/name: search-ruler
    app.kubernetes.io/managed-by: kustomize
  name: ruleraction-sample
spec:
  firingInterval: 1m
  webhook:
    url: https://webhook.site/7688d5a6-af64-40d4-9991-01cb3b9035a7
    verb: POST
    headers: {}
    validator: alertmanager
    # credentials:   
    #   secretRef:
    #     name: alertmanager-credentials
    #     keyUsername: username
    #     keyPassword: password
