apiVersion: searchruler.freepik.com/v1alpha1
kind: QueryConnector
metadata:
  labels:
    app.kubernetes.io/name: search-ruler
    app.kubernetes.io/managed-by: kustomize
  name: queryconnector-sample
spec:

  # URL for the query connector. We will execute the queries in this URL
  url: "https://127.0.0.1:9200"

  # Additional headers if needed for the connection
  headers: {}

  # Skip certificate verification if the connection is HTTPS
  tlsSkipVerify: true

  # Interval to check secret credentials for any changes
  # Default value is 1m
  #syncInterval: 1m

  # Certificates to use for the connection
  certificates:
    secretRef:
      name: elasticsearch-main-certificates
      namespace: default
      keyCA: ca.crt
      keyCert: cert.crt
      keyKey: key.pem

  # Secret reference to get the credentials if needed for the connection
  credentials:
    secretRef:
      name: elasticsearch-main-credentials
      namespace: default
      keyUsername: username
      keyPassword: password
