apiVersion: searchruler.prosimcorp.com/v1alpha1
kind: RulerAction
metadata:
  labels:
    app.kubernetes.io/name: search-ruler
    app.kubernetes.io/managed-by: kustomize
  name: ruleraction-sample
spec:
  webhook:
    url: https://webhook.site/3f2e28af-68b2-47bd-b603-f8abcdf2ac93
    verb: POST
    headers: {}

    #validator: alertmanager

    # credentials:   
    #   secretRef:
    #     name: alertmanager-credentials
    #     keyUsername: username
    #     keyPassword: password
